apiVersion: batch/v1
kind: CronJob
metadata:
  name: xfusion
spec:
  schedule: "30 8 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-xfusion
            image: httpd:latest
            args:
            - /bin/sh
            - -c
            - echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure